### ISSUE TITLE
GitHub Actions の導入

### ISSUE THREAD

**Issue by matumoto1234** [matumoto1234/library#3]
これは #2 が終わってからでいいかな

`.github/workflows/verify.yaml` を作成する

暫定的な内容は下記

```yaml
name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: oj-verify all
```
